name: HorseLunge
version: ${project.version}
main: me.dkflab.horselunge.HorseLunge
api-version: 1.16
commands:
  lunge:
    description: Get lunge wand
  horse:
    description: Check horse food and water levels.
  vaccine:
    description: Remove illness from horse